// <auto-generated />
namespace news.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_image));
        
        string IMigrationMetadata.Id
        {
            get { return "202105251636434_edit_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
